No valid candidates found for failure: numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2